### GET all users

GET http://localhost:3000/api/users HTTP/1.1

### GET a single user

GET http://localhost:3000/api/users/Leon HTTP/1.1

### GET a single user which doesn't exist

GET http://localhost:3000/api/users/Noel HTTP/1.1

### Delete a user
DELETE http://localhost:3000/api/users/Leon HTTP/1.1

### POST a user
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name": "Maggy"
} 